version: "3.3"

services:
  tiddlywiki:
    build:
      context: ./tiddlywiki
      args:
        TW_VERSION: ${TW_VERSION}
        TW_USERNAME: ${TW_USERNAME}
        TW_PASSWORD: ${TW_PASSWORD}
    container_name: tiddlywiki
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../app:/app
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
