version: "3.3"

services:
  tiddlywiki:
    build:
      context: ./tiddlywiki
      args:
        TW_VERSION: ${TW_VERSION}
        TW_USERNAME: ${TW_USERNAME}
        TW_PASSWORD: ${TW_PASSWORD}
    container_name: tiddlywiki
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../app:/app
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: ${FQDN}
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
